// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import DashboardOutlined from '/Users/minyi/workspace/node_ws/react-flow/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DashboardOutlined';
import SettingOutlined from '/Users/minyi/workspace/node_ws/react-flow/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import DeploymentUnitOutlined from '/Users/minyi/workspace/node_ws/react-flow/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/DeploymentUnitOutlined';
import ApiOutlined from '/Users/minyi/workspace/node_ws/react-flow/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ApiOutlined';
import ToolOutlined from '/Users/minyi/workspace/node_ws/react-flow/node_modules/.pnpm/@ant-design+icons@4.8.3_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@ant-design/icons/es/icons/ToolOutlined';
export default { DashboardOutlined, SettingOutlined, DeploymentUnitOutlined, ApiOutlined, ToolOutlined };
