// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/","redirect":"/dashboard","parentId":"ant-design-pro-layout","id":"1"},"2":{"name":"仪表盘","path":"/dashboard","icon":"DashboardOutlined","parentId":"ant-design-pro-layout","id":"2"},"3":{"name":"规则引擎","path":"/rule-engine","icon":"SettingOutlined","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"规则管理","path":"/rule-engine/rules","parentId":"3","id":"4"},"5":{"name":"规则编辑器","path":"/rule-engine/editor","parentId":"3","id":"5"},"6":{"name":"规则测试","path":"/rule-engine/test","parentId":"3","id":"6"},"7":{"name":"工作流","path":"/workflow","icon":"DeploymentUnitOutlined","parentId":"ant-design-pro-layout","id":"7"},"8":{"name":"工作流设计器","path":"/workflow/designer","parentId":"7","id":"8"},"9":{"name":"工作流管理","path":"/workflow/manage","parentId":"7","id":"9"},"10":{"name":"流程实例","path":"/workflow/instances","parentId":"7","id":"10"},"11":{"name":"Flowable","path":"/flowable","icon":"ApiOutlined","parentId":"ant-design-pro-layout","id":"11"},"12":{"name":"流程定义","path":"/flowable/definitions","parentId":"11","id":"12"},"13":{"name":"任务管理","path":"/flowable/tasks","parentId":"11","id":"13"},"14":{"name":"流程监控","path":"/flowable/monitor","parentId":"11","id":"14"},"15":{"name":"系统管理","path":"/system","icon":"ToolOutlined","parentId":"ant-design-pro-layout","id":"15"},"16":{"name":"用户管理","path":"/system/users","parentId":"15","id":"16"},"17":{"name":"角色管理","path":"/system/roles","parentId":"15","id":"17"},"18":{"name":"权限管理","path":"/system/permissions","parentId":"15","id":"18"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__Dashboard__index" */'@/pages/Dashboard/index.tsx')),
'3': React.lazy(() => import('./EmptyRoute')),
'4': React.lazy(() => import(/* webpackChunkName: "p__RuleEngine__Rules__index" */'@/pages/RuleEngine/Rules/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__RuleEngine__Editor__index" */'@/pages/RuleEngine/Editor/index.tsx')),
'6': React.lazy(() => import(/* webpackChunkName: "p__RuleEngine__Test__index" */'@/pages/RuleEngine/Test/index.tsx')),
'7': React.lazy(() => import('./EmptyRoute')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Workflow__Designer__index" */'@/pages/Workflow/Designer/index.tsx')),
'9': React.lazy(() => import(/* webpackChunkName: "p__Workflow__Manage__index" */'@/pages/Workflow/Manage/index.tsx')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Workflow__Instances__index" */'@/pages/Workflow/Instances/index.tsx')),
'11': React.lazy(() => import('./EmptyRoute')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Flowable__Definitions__index" */'@/pages/Flowable/Definitions/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Flowable__Tasks__index" */'@/pages/Flowable/Tasks/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Flowable__Monitor__index" */'@/pages/Flowable/Monitor/index.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__System__Users__index" */'@/pages/System/Users/index.tsx')),
'17': React.lazy(() => import(/* webpackChunkName: "p__System__Roles__index" */'@/pages/System/Roles/index.tsx')),
'18': React.lazy(() => import(/* webpackChunkName: "p__System__Permissions__index" */'@/pages/System/Permissions/index.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/minyi/workspace/node_ws/react-flow/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
